### ISSUE TITLE
Unable to use the cli on M1 Mac 

### ISSUE THREAD

**Issue by guillaumemaka** [microsoft/team-explorer-everywhere#356] opened 2023-06-16 13:52 UTC
Greetings,

When I try to use the cli for example `tf eula` I got this exception

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Ljava/lang/String;)Ljava/lang/String;
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Native Method)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.getEnvironmentVariable(NativePlatformMisc.java:121)
	at com.microsoft.tfs.jni.PlatformMiscUtils.getEnvironmentVariable(PlatformMiscUtils.java:47)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:96)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.client.common.logging.TELoggingConfiguration.configure(TELoggingConfiguration.java:38)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:23)
```

I got this error on my intel mac, the error was that it cannot load the .jnilib files.

I was able to authorize load action in FileVault, but not on my M1 mac there is no security prompt. 

Anyone else experience this issue?

OS Info

Nom du modèle :	MacBook Pro
Identifiant du modèle :	MacBookPro18,3
Puce :	Apple M1 Pro
Nombre total de cœurs :	10 (8 de performance et 2 d’efficacité)
Mémoire :	32 Go
Version du programme interne du système :	8422.121.1

Java Version (install from sdkman)

openjdk version "1.8.0_352"
OpenJDK Runtime Environment Corretto-8.352.08.1 (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM Corretto-8.352.08.1 (build 25.352-b08, mixed mode)

**Comment by eric-milles** [comment] 2023-10-10 16:16
duplicate of #334

**Closed by eric-milles** 2023-10-10 16:16 UTC

**Comment by wonderfuer** [comment] 2024-03-23 02:44
可以参考：https://github.com/JetBrains/team-explorer-everywhere/releases/tag/14.135.3

**Comment by altmoket** [comment] 2025-01-09 23:00
Hi,
I am experiencing the same issue when running the tf eula command:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(java.lang.String)'
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Native Method)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.getEnvironmentVariable(NativePlatformMisc.java:121)
	at com.microsoft.tfs.jni.PlatformMiscUtils.getEnvironmentVariable(PlatformMiscUtils.java:47)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:96)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.client.common.logging.TELoggingConfiguration.configure(TELoggingConfiguration.java:41)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:23)
```
Has anyone found a solution or workaround for this issue?

**Comment by spuliy** [comment] 2025-05-13 18:41
@altmoket Have you found a solution for this?
