### ISSUE TITLE
Tee CLC Add with tfignore not working correctly under linux

### ISSUE THREAD

**Issue by KlausStein** [microsoft/team-explorer-everywhere#159] opened 2017-01-05 14:33 UTC
We use tee clc 14.0.3 under redhat linux 7.3 in combination with a TFS Server 2015 U2.1. Due to the size of your workspace we have to use a server workspace. We want to use the tf add command  in combination with .tfignore files to filter out unwanted content. Under windows this is working like a charm, but under linux is does not. 

We setup folder structure like this:
BaseFold
-- .tfignore
--/src
---- multiple levels of subfolders
---- new Content files

Some of the content files are filtered out by .tfignore. We call "tf add ./src/*" from baseFold and would think that only non ignored files are added to the workspace. But all files will get added. 
After adding the line 
**echo "Parameters: $@"** 
right before the exec in the tf script we can see in the log file, that the $@ variable already contains the expanded file names and not the passed wildcard pattern. As tf add is not using tfignore on non-wildcard paths, this is kind of to be expected, but tf script is a little bad in handling.

After that I set the pattern into single quotes, so the $@ now really shows a pattern, but now the command simply does nothing. The command ends without message and no files are added. 

To investigate the problem further, I had a real hard time to configure the logger to bring more info, but finally I found out that there is a nullpointerexception in FileSystemWalker.java at line 503 when calling "tf add './src/*'". 

The source code of FileSystemWalker inspired me to try the command like this  "tf add -recursive ./src/" and bang that worked correctly, besides the fact that folders with only ignored files (empty for TFS) are also added to source control. With our big workspaces and a lot of folders hitting that condition, this is also a bad solution. 

So now I am stuck with a bunch of errors and faulty behavior:
1. "tf add ./src/*" is not using the wildcard path in tf because wildcard is already resolved by Linux
2. "tf add './src/*'" throws a null pointer exception 
3. "tf add -recursive ./src/" is adding empty folders to tfs

Is there any chance to get my use case running? 

Best regards, 
Klaus

**Comment by aumanjoa** [comment] 2017-01-16 07:58
Same Problem here any suggestions?

**Comment by KlausStein** [comment] 2017-01-16 07:59
Hi Guys, 

no one knowing about such a problem? In general it also looks like the wrong handling of folders under Linux results in problems when undoing changes and deleting substructures through TEE Eclipse Plugin. Then only files get deleted and folders stay. 

Best regards, 
Klaus

**Comment by leantk** [comment] 2017-01-18 18:32
Hi @KlausStein,

I'm trying to reproduce your issue and am seeing the same behavior you described on Linux for when you "tf add ./src/*". I see the exact same behavior (adding files that should be ignored) on Windows though. By chance, are you using tf.exe on Windows and not tf.cmd? tf.exe is specialized for Windows that's why I ask. Either way it's a bug that the wildcard adds the ignored files and I'm adding it to our backlog. Thanks for reporting this.

Thanks again,
-Leah

**Comment by KlausStein** [comment] 2017-01-19 08:13
Hi Leah, 

I did the tests and Windows again and you are right. I must have used tf without extension and so my windows machine took the tf.exe one. Sorry for that mistake, but as you said the bug is there also on windows.  

I also see the problem of adding folders to version control under windows. Even empty folders are added. This leads to the problem that if you want to Undo the complete folder hierarchy in eclipse, the folders are only undone if there is no further empty folder or file inside. So you have to execute undo for each level of folders recursively. Visual Studio can handle that with one Undo command on top level correctly. So either the commandline should add empty folders only if the folder is specified directly (not with wildcard) and/or eclipse should be able to handle multiple levels of empty folders in a undo operation. 
Maybe this is another bug.

Best regards, 
Klaus

**Comment by AlexRukhlin** [comment] 2017-04-07 14:35
Hi,
Try to use `tf add -r ./src` command. 

Unlike in Git, folders in TFVC are first class citizens by design. So, if the folder you're adding is empty, it will be added as is.

Alex

**Comment by KlausStein** [comment] 2017-04-10 06:02
Hi Alex, 

thanks for the info, having empty folder under source control is not nice, but if this is the way "you" (Microsoft) is thinking about that, than ok. We will find a way around. But the first two commands still are reacting either not as expected (see faulty behavior 1) or actually throwing errors (see fault behavior 2). So what is the reason to declare this issue not to be fixed? Everywhere Microsoft is promoting their way to XPlat and then a Bug is not to be fixed because it is only happening in Linux?

Best regards,
Klaus

**Comment by leantk** [comment] 2017-04-11 16:48
Hi @KlausStein,

Instead of doing `tf add ./src/* `did you try `tf add -r ./src` to recursively add the files under the folder? That _should_ add your files but ignore the ones in the .tfignore but if not please let us know. With the recursive flag passed that should handle the files under the directory appropriately.

Thanks,
-Leah

**Comment by KlausStein** [comment] 2017-04-12 06:14
Hi Leah, 

is there a difference between "tf add -r ./src" and "tf add -r ./src/"? Because if not, then I already tried that (see approach 3 in first post) and this command is adding empty folders. As @AlexRukhlin told me, this seems to be intended as MS is seeing folders as "first class citizens". Actually I bet to find no one else saying empty folders in source control are best practice, but I am fine with that. So we have to find a way to get rid of the empty folders after performing the add and before the commit operation.
But besides that each Nullpointer Reference Exception that comes within normal usage of a tool is actually a bug, no matter if there is a work around or not. So removing the bug tag on this is only beatifying bug statistics, but not helping anybody out there.

Best regards, 
Klaus

**Comment by leantk** [comment] 2017-04-12 14:33
Hi @KlausStein,

Ok I'm sorry for the misunderstanding. Alex fixed the null pointer exception with this commit https://github.com/Microsoft/team-explorer-everywhere/commit/0b746b606e90a82e41096c159424b8fc9f20de02 and it looks like it was released in version 1.114.0 of the plugin. I thought you were still having issues with adding recursively and the empty folders. That's why Alex added the wontfix label because that is an implementation detail that we cannot change. 

Again sorry for the mix-up,
-Leah

**Closed** 2021-12-10 17:58 UTC
Labels: wontfix
